### PR TITLE
Add ATtiny13a support

### PR DESCRIPTION
**Pull request by aaronaverill**
Added support for ATtiny13a flashing. Added common board definition class constants to simplify user code examples.

### CODE REVIEW

**Comment by ladyada** [comment]
ok please check travis!
next up, is there a way people can DIY their own definition so they dont have to edit the boards list in avrprog.py?

**Comment by aaronaverill** [comment]
> next up, is there a way people can DIY their own definition so they dont have to edit the boards list in avrprog.py?

Yup, same as before, people can create an arbitrary mapping for chip properties in their program and pass it to the avrprog methods. I've simply extracted the 3(+1) common examples into a class constant that can be referenced with a one-liner instead of copy/paste.

**Comment by ladyada** [comment]
ok leave ne of them in so people knw how to do it, because now there is no example

**Comment by aaronaverill** [comment]
M'kay. It's a legit point since people will be using avrprog mpy and not looking at the source outside the examples and the convenience of pre-defined chips makes it look a bit "black magic" even if it's making 95% of the use cases easier :)

Added an example to the mega2560 and provided link to avrdude.conf file in version control.

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
thank uuuuu!

**Comment by ladyada** [comment]
@caternuson plz bump release :)

**Pull request merged**
